version: "3.9"
services:
  ceramic-integration-test:
    image: node:16
    volumes:
      - ./database-client:/passport/database-client
      - ./schemas:/passport/schemas
      - ./types:/passport/types
      - ./lerna.json:/passport/lerna.json
      - ./package.json:/passport/package.json
      - ./tsconfig.json:/passport/tsconfig.json
      - ./tsconfig.settings.json:/passport/tsconfig.settings.json
      - ./yarn.lock:/passport/yarn.lock
    entrypoint:
      ["sh", "/passport/database-client/integration-tests/run-ceramic-tests.sh"]
