name: Add issues to passport project

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      issues: read|write
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/gitcoinco/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}
