name: Deploy Ceramic Mainnet Node

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit ref"
        required: true
        type: string

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: infra/ceramic-mainnet/package-lock.json
      # Update the pulumi stack with new image
      - run: |
          npm install
          pulumi stack select -c gitcoin/ceramic/mainnet-node
          pulumi config -s gitcoin/ceramic/mainnet-node set aws:region us-east-1 --non-interactive
        working-directory: infra/ceramic-mainnet
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v3
        id: pulumi
        with:
          command: up
          stack-name: gitcoin/ceramic/mainnet-node

          upsert: false
          work-dir: infra/ceramic-mainnet
        env:
          ROUTE_53_ZONE: ${{ secrets.ROUTE53_ZONE_ID_PRODUCTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          DOMAIN: passport-iam.gitcoin.co
          RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
