name: Deploy Ceramic Testnet Node

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit ref"
        required: true
        type: string

jobs:
  deploy-ceramic-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: infra/ceramic-testnet/package-lock.json
      # Update the pulumi stack with new image
      - run: |
          npm install
          pulumi stack select -c gitcoin/ceramic/testnet-node
          pulumi config -s gitcoin/ceramic/testnet-node set aws:region us-east-1 --non-interactive
        working-directory: infra/ceramic-testnet
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v3
        id: pulumi
        with:
          command: up
          stack-name: gitcoin/ceramic/testnet-node
          upsert: false
          work-dir: infra/ceramic-testnet
        env:
          ROUTE_53_ZONE: ${{ secrets.ROUTE53_ZONE_ID_STAGING }}
          DOMAIN: ${{ secrets.DOMAIN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
