name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Lerna Bootstrap
        run: lerna bootstrap
      - name: Run Tests
        run: yarn test
      - name: Run Linter
        run: yarn lint
