name: Deploy Signer to Staging
on:
  workflow_dispatch:
    inputs:
      # commit hash (for frontend deploy to fleek)
      commit:
        description: "Branch/Commit ref"
        default: "origin/main"
        type: string
jobs:
  deploy-signer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout staging-signer
        run: |
          git fetch
          git checkout -b staging-signer origin/staging-signer
          git reset --hard ${{ github.event.inputs.commit }}
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/gitcoinco/passport.git
          git push origin staging-signer -f
